#!/bin/sh

cd "/home/rvardhineni/NC State Lectures/CSC 591 - DevOps/HW4/DevOps_HW4_AdvancedDocker/Docker Deploy/App"

sudo docker rmi ncsu-app
sudo docker build -t ncsu-app .

sudo docker tag -f ncsu-app localhost:5000/ncsu:latest

sudo docker push localhost:5000/ncsu:latest

