client-ambassador:
  image: svendowideit/ambassador
  container_name: "client-ambassador"
  expose:
   - "6379"
  environment:
   - "REDIS_PORT_6379_TCP=tcp://192.168.0.15:6379"

client-redis:
  image: relateiq/redis-cli
  container_name: "client-redis"
  links:
   - client-ambassador:redis

